name: Sync default branches
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: self-hosted
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Opening pull request to resizes
        id: pull_resizes
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "hotfix"
          CONTENT_COMPARISON: true
          PULL_REQUEST_AUTO_MERGE_METHOD: 'rebase'
