name: Sync default branches
on:
  push:
    branches:
      - master

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  sync-branches:
    runs-on: [ ubuntu-latest ]
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "bot@mail.com"
      - name: Update Test Branch
        run: |
          git checkout master
          git fetch origin
          git checkout hotfix
          git rebase master
          git push --force-with-lease