name: Sync default branches
on:
  push:
    branches:
      - master

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  sync-branches:
    runs-on: [ ubuntu-latest ]
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Opening pull request to resizes
        id: pull_resizes
        uses: sansx/sync-branches@v1.0.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "hotfix"
          CONTENT_COMPARISON: true
          PULL_REQUEST_AUTO_MERGE_METHOD: 'rebase'
