name: Sync default branches
on:
  push:
    branches:
      - master

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git User
        run: |
          git config user.name "Branch Sync"
          git config user.email "foundation@mercafacil.com"
      - name: Sync [hotfix] branch
        id: sync-hotfix
        continue-on-error: true  # Allows the job to continue
        run: |
          git checkout ${{ github.event.repository.default_branch }}
          git fetch origin
          git checkout hotfix
          git rebase ${{ github.event.repository.default_branch }}
          git push --force-with-lease
      - name: Check [cons-eng-beta] exists
        continue-on-error: true  # Allows the job to continue
        run: |
          if git ls-remote --exit-code --heads origin cons-eng-beta; then
            echo "exists-cons-eng-beta=true" >> $GITHUB_ENV
          else
            echo "exists-cons-eng-beta=false" >> $GITHUB_ENV
          fi
      - name: Sync [cons-eng-beta] branch
        continue-on-error: true  # Allows the job to continue
        if: env.exists-cons-eng-beta == 'true'
        run: |
          git checkout ${{ github.event.repository.default_branch }}
          git fetch origin
          git checkout cons-eng-beta
          git rebase ${{ github.event.repository.default_branch }}
          git push --force-with-lease
      - name: Send Slack Notification
        if: steps.sync-hotfix.outcome == 'failure'
        uses: slackapi/slack-github-action@v1
        with:
          slack-message: "🚨 *GitHub Action Failed!* Repo: ${{ github.repository }}"
        env:
          SLACK_BOT_TOKEN: ${{ vars.SYNC_BRANCH_SLACK_WEBHOOK_URL }}
