name: Sync default branches
on:
  push:
    branches:
      - master

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git User
        run: |
          git config user.name "Branch Sync"
          git config user.email "foundation@mercafacil.com"
      - name: Sync [hotfix] branch
        id: syncHotfix
        continue-on-error: true  # Allows the job to continue
        run: |
          git checkout ${{ github.event.repository.default_branch }}
          git fetch origin
          git checkout hotfix
          git rebase ${{ github.event.repository.default_branch }}
          git push --force-with-lease
      - name: Check [cons-eng-beta] exists
        continue-on-error: true  # Allows the job to continue
        run: |
          if git ls-remote --exit-code --heads origin cons-eng-beta; then
            echo "exists-cons-eng-beta=true" >> $GITHUB_ENV
          else
            echo "exists-cons-eng-beta=false" >> $GITHUB_ENV
          fi
      - name: Sync [cons-eng-beta] branch
        continue-on-error: true  # Allows the job to continue
        if: env.exists-cons-eng-beta == 'true'
        run: |
          git checkout ${{ github.event.repository.default_branch }}
          git fetch origin
          git checkout cons-eng-beta
          git rebase ${{ github.event.repository.default_branch }}
          git push --force-with-lease
  notify-slack:
    if: steps.syncHotfix.outcome == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": ":x: *GitHub Action Failed!*\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCommit: ${{ github.sha }}\nTriggered by: ${{ github.actor }}",
            "username": "GitHub Actions",
            "icon_emoji": ":github:"
          }' ${{ env.SYNC_BRANCH_SLACK_WEBHOOK_URL }}
